In [4]:
import pandas as pd

df = pd.read_csv("data.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130,132,0,2,185,0,0.0,?,?,?,0
1,29,1,2,120,243,0,0,160,0,0.0,?,?,?,0
2,29,1,2,140,?,0,0,170,0,0.0,?,?,?,0
3,30,0,1,170,237,0,1,170,0,0.0,?,?,6,0
4,31,0,2,100,219,0,1,150,0,0.0,?,?,?,0

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         294 non-null    int64
 1   sex         294 non-null    int64
 2   cp          294 non-null    int64
 3   trestbps    294 non-null    object
 4   chol        294 non-null    object
 5   fbs         294 non-null    object
 6   restecg     294 non-null    object
 7   thalach     294 non-null    object
 8   exang       294 non-null    object
 9   oldpeak     294 non-null    float64
 10  slope       294 non-null    object
 11  ca          294 non-null    object
 12  thal        294 non-null    object
 13  num         294 non-null    int64
dtypes: float64(1), int64(4), object(9)
memory usage: 32.3+ KB

In [7]:
df.describe().T

            count       mean       std   min   25%   50%   75%   max
age         294.0  47.826531  7.811812  28.0  42.0  49.0  54.0  66.0
sex         294.0   0.724490  0.447533   0.0   0.0   1.0   1.0   1.0
cp          294.0   2.982993  0.965117   1.0   2.0   3.0   4.0   4.0
oldpeak     294.0   0.586054  0.908648   0.0   0.0   0.0   1.0   5.0
num         294.0   0.360544  0.480977   0.0   0.0   0.0   1.0   1.0

In [14]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num       '],
      dtype='object')

In [11]:
df.trestbps.value_counts(dropna=False)

trestbps
120    65
130    54
140    50
150    23
110    21
160    20
125     8
100     6
180     6
145     5
135     5
170     5
112     3
122     2
124     2
115     2
118     2
190     1
98      1
105     1
142     1
?       1
108     1
132     1
113     1
92      1
106     1
200     1
138     1
136     1
128     1
155     1
Name: count, dtype: int64